version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      DATABASE_URL: mysql://root:12345678@db:3306/TasksDb
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - my-network

  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: TaskDb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  db-data:

networks:
  my-network:
